<?php

namespace HaruyaNishikubo\Transporter\Models\Node\Entity\Logiless;

use HaruyaNishikubo\Transporter\Models\Node\Entity\Entity;

class SalesOrderEntity extends Entity
{
    protected string $table_name = 'sales_order';

    protected array $fields = [
        'id' => self::FIELD_TYPE_INT64,
        'code' => self::FIELD_TYPE_STRING,
        'parent_code' => self::FIELD_TYPE_STRING,
        'document_status' => self::FIELD_TYPE_STRING,
        'allocation_status' => self::FIELD_TYPE_STRING,
        'delivery_status' => self::FIELD_TYPE_STRING,
        'incoming_payment_status' => self::FIELD_TYPE_STRING,
        'authorization_status' => self::FIELD_TYPE_STRING,
        'customer_code' => self::FIELD_TYPE_STRING,
        'buyer_name1' => self::FIELD_TYPE_STRING,
        'buyer_name2' => self::FIELD_TYPE_STRING,
        'buyer_name_kana1' => self::FIELD_TYPE_STRING,
        'buyer_name_kana2' => self::FIELD_TYPE_STRING,
        'buyer_country' => self::FIELD_TYPE_STRING,
        'buyer_post_code' => self::FIELD_TYPE_STRING,
        'buyer_prefecture' => self::FIELD_TYPE_STRING,
        'buyer_address1' => self::FIELD_TYPE_STRING,
        'buyer_address2' => self::FIELD_TYPE_STRING,
        'buyer_address3' => self::FIELD_TYPE_STRING,
        'buyer_phone' => self::FIELD_TYPE_STRING,
        'buyer_fax' => self::FIELD_TYPE_STRING,
        'buyer_email' => self::FIELD_TYPE_STRING,
        'recipient_name1' => self::FIELD_TYPE_STRING,
        'recipient_name2' => self::FIELD_TYPE_STRING,
        'recipient_name_kana1' => self::FIELD_TYPE_STRING,
        'recipient_name_kana2' => self::FIELD_TYPE_STRING,
        'recipient_country' => self::FIELD_TYPE_STRING,
        'recipient_post_code' => self::FIELD_TYPE_STRING,
        'recipient_prefecture' => self::FIELD_TYPE_STRING,
        'recipient_address1' => self::FIELD_TYPE_STRING,
        'recipient_address2' => self::FIELD_TYPE_STRING,
        'recipient_address3' => self::FIELD_TYPE_STRING,
        'recipient_phone' => self::FIELD_TYPE_STRING,
        'recipient_fax' => self::FIELD_TYPE_STRING,
        'recipient_email' => self::FIELD_TYPE_STRING,
        'subtotal' => self::FIELD_TYPE_INT64,
        'use_point' => self::FIELD_TYPE_INT64,
        'use_coupon' => self::FIELD_TYPE_INT64,
        'delivery_fee' => self::FIELD_TYPE_INT64,
        'sundry_fee' => self::FIELD_TYPE_INT64,
        'discount' => self::FIELD_TYPE_INT64,
        'tax_processing_method' => self::FIELD_TYPE_STRING,
        'tax_rounding_method' => self::FIELD_TYPE_STRING,
        'document_tax_rate' => self::FIELD_TYPE_INT64,
        'tax_total' => self::FIELD_TYPE_INT64,
        'total' => self::FIELD_TYPE_INT64,
        'payment_method' => self::FIELD_TYPE_STRING,
        'delivery_method' => self::FIELD_TYPE_STRING,
        'delivery_package_quantity' => self::FIELD_TYPE_INT64,
        'express_type' => self::FIELD_TYPE_STRING,
        'delivery_temperature_control' => self::FIELD_TYPE_STRING,
        'scheduled_shipping_date' => self::FIELD_TYPE_DATE,
        'delivery_preferred_date' => self::FIELD_TYPE_DATE,
        'delivery_preferred_time_zone' => self::FIELD_TYPE_STRING,
        'is_isolated_area' => self::FIELD_TYPE_BOOLEAN,
        'delivery_tracking_number' => self::FIELD_TYPE_STRING,
        'buyer_comment' => self::FIELD_TYPE_STRING,
        'merchant_comment' => self::FIELD_TYPE_STRING,
        'statement_notes' => self::FIELD_TYPE_STRING,
        'picking_notes' => self::FIELD_TYPE_STRING,
        'way_bill_notes' => self::FIELD_TYPE_STRING,
        'gift' => self::FIELD_TYPE_BOOLEAN,
        'wrapping' => self::FIELD_TYPE_BOOLEAN,
        'noshi' => self::FIELD_TYPE_BOOLEAN,
        'attr1' => self::FIELD_TYPE_STRING,
        'attr2' => self::FIELD_TYPE_STRING,
        'attr3' => self::FIELD_TYPE_STRING,
        'attr4' => self::FIELD_TYPE_STRING,
        'attr5' => self::FIELD_TYPE_STRING,
        'attr6' => self::FIELD_TYPE_STRING,
        'attr7' => self::FIELD_TYPE_STRING,
        'attr8' => self::FIELD_TYPE_STRING,
        'attr9' => self::FIELD_TYPE_STRING,
        'attr10' => self::FIELD_TYPE_STRING,
        'waiting_for_confirmation' => self::FIELD_TYPE_BOOLEAN,
        'shipping_confirmed' => self::FIELD_TYPE_BOOLEAN,
        'is_multiple_deliveries' => self::FIELD_TYPE_BOOLEAN,
        'subscription_id' => self::FIELD_TYPE_INT64,
        'subscription_delivery_number' => self::FIELD_TYPE_INT64,
        'subscription_next_delivery_date' => self::FIELD_TYPE_DATE,
        'posting_date' => self::FIELD_TYPE_TIMESTAMP,
        'total_quantity' => self::FIELD_TYPE_INT64,
        'purchasing_times' => self::FIELD_TYPE_INT64,
        'tags' => self::FIELD_TYPE_JSON,
        'ordered_at' => self::FIELD_TYPE_TIMESTAMP,
        'finished_at' => self::FIELD_TYPE_TIMESTAMP,
        'created_at' => self::FIELD_TYPE_TIMESTAMP,
        'updated_at' => self::FIELD_TYPE_TIMESTAMP,
        'lines' => self::FIELD_TYPE_JSON,
        'outbound_deliveries' => self::FIELD_TYPE_JSON,
        'store' => self::FIELD_TYPE_JSON,
        'document_date' => self::FIELD_TYPE_DATE,
    ];
}
