<?php

namespace HaruyaNishikubo\Transporter\Models\Node\Entity\Shopify\Rest;

use HaruyaNishikubo\Transporter\Models\Node\Entity\Entity;

class OrderEntity extends Entity
{
    protected string $table_name = 'orders';

    protected array $fields = [
        'id' => self::FIELD_TYPE_INT64,
        'admin_graphql_api_id' => self::FIELD_TYPE_STRING,
        'app_id' => self::FIELD_TYPE_STRING,
        'browser_ip' => self::FIELD_TYPE_STRING,
        'buyer_accepts_marketing' => self::FIELD_TYPE_BOOLEAN,
        'cancel_reason' => self::FIELD_TYPE_STRING,
        'cancelled_at' => self::FIELD_TYPE_TIMESTAMP,
        'cart_token' => self::FIELD_TYPE_STRING,
        'checkout_id' => self::FIELD_TYPE_INT64,
        'checkout_token' => self::FIELD_TYPE_STRING,
        'client_details' => self::FIELD_TYPE_JSON,
        'closed_at' => self::FIELD_TYPE_TIMESTAMP,
        'confirmed' => self::FIELD_TYPE_BOOLEAN,
        'contact_email' => self::FIELD_TYPE_STRING,
        'created_at' => self::FIELD_TYPE_TIMESTAMP,
        'currency' => self::FIELD_TYPE_STRING,
        'current_subtotal_price' => self::FIELD_TYPE_FLOAT64,
        'current_subtotal_price_set' => self::FIELD_TYPE_JSON,
        'current_total_discounts' => self::FIELD_TYPE_FLOAT64,
        'current_total_discounts_set' => self::FIELD_TYPE_JSON,
        'current_total_duties_set' => self::FIELD_TYPE_JSON,
        'current_total_price' => self::FIELD_TYPE_FLOAT64,
        'current_total_price_set' => self::FIELD_TYPE_JSON,
        'current_total_tax' => self::FIELD_TYPE_FLOAT64,
        'current_total_tax_set' => self::FIELD_TYPE_JSON,
        'customer_locale' => self::FIELD_TYPE_STRING,
        'device_id' => self::FIELD_TYPE_INT64,
        'discount_codes' => self::FIELD_TYPE_JSON,
        'email' => self::FIELD_TYPE_STRING,
        'estimated_taxes' => self::FIELD_TYPE_BOOLEAN,
        'financial_status' => self::FIELD_TYPE_STRING,
        'fulfillment_status' => self::FIELD_TYPE_STRING,
        'gateway' => self::FIELD_TYPE_STRING,
        'landing_site' => self::FIELD_TYPE_STRING,
        'landing_site_ref' => self::FIELD_TYPE_STRING,
        'location_id' => self::FIELD_TYPE_INT64,
        'name' => self::FIELD_TYPE_STRING,
        'note' => self::FIELD_TYPE_STRING,
        'note_attributes' => self::FIELD_TYPE_JSON,
        'number' => self::FIELD_TYPE_INT64,
        'order_number' => self::FIELD_TYPE_INT64,
        'order_status_url' => self::FIELD_TYPE_STRING,
        'original_total_duties_set' => self::FIELD_TYPE_JSON,
        'payment_gateway_names' => self::FIELD_TYPE_JSON,
        'phone' => self::FIELD_TYPE_STRING,
        'presentment_currency' => self::FIELD_TYPE_STRING,
        'processed_at' => self::FIELD_TYPE_TIMESTAMP,
        'processing_method' => self::FIELD_TYPE_STRING,
        'reference' => self::FIELD_TYPE_STRING,
        'referring_site' => self::FIELD_TYPE_STRING,
        'source_identifier' => self::FIELD_TYPE_STRING,
        'source_name' => self::FIELD_TYPE_STRING,
        'source_url' => self::FIELD_TYPE_STRING,
        'subtotal_price' => self::FIELD_TYPE_FLOAT64,
        'subtotal_price_set' => self::FIELD_TYPE_JSON,
        'tags' => self::FIELD_TYPE_STRING,
        'tax_lines' => self::FIELD_TYPE_JSON,
        'taxes_included' => self::FIELD_TYPE_BOOLEAN,
        'test' => self::FIELD_TYPE_BOOLEAN,
        'token' => self::FIELD_TYPE_STRING,
        'total_discounts' => self::FIELD_TYPE_FLOAT64,
        'total_discounts_set' => self::FIELD_TYPE_JSON,
        'total_line_items_price' => self::FIELD_TYPE_FLOAT64,
        'total_line_items_price_set' => self::FIELD_TYPE_JSON,
        'total_outstanding' => self::FIELD_TYPE_FLOAT64,
        'total_price' => self::FIELD_TYPE_FLOAT64,
        'total_price_set' => self::FIELD_TYPE_JSON,
        'total_price_usd' => self::FIELD_TYPE_FLOAT64,
        'total_shipping_price_set' => self::FIELD_TYPE_JSON,
        'total_tax' => self::FIELD_TYPE_FLOAT64,
        'total_tax_set' => self::FIELD_TYPE_JSON,
        'total_tip_received' => self::FIELD_TYPE_FLOAT64,
        'total_weight' => self::FIELD_TYPE_INT64,
        'updated_at' => self::FIELD_TYPE_TIMESTAMP,
        'user_id' => self::FIELD_TYPE_INT64,
        'billing_address' => self::FIELD_TYPE_JSON,
        'customer' => self::FIELD_TYPE_JSON,
        'discount_applications' => self::FIELD_TYPE_JSON,
        'fulfillments' => self::FIELD_TYPE_JSON,
        'line_items' => self::FIELD_TYPE_JSON,
        'payment_details' => self::FIELD_TYPE_JSON,
        'payment_terms' => self::FIELD_TYPE_JSON,
        'refunds' => self::FIELD_TYPE_JSON,
        'shipping_address' => self::FIELD_TYPE_JSON,
        'shipping_lines' => self::FIELD_TYPE_JSON,
    ];
}
